project_id = "yckcdxtatwolzilboahx"

[functions.ai-search]
verify_jwt = false

[functions.ai-analyze]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.property-assistant]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.realtime-token]
verify_jwt = true

[functions.fetch-property]
verify_jwt = false

